#! /bin/sh
# this bash script will run a number of instances of src/ceres. 
# It takes two arguments
# 1: a file that contains a list of configuration files
# 2: number of cpus 

start_time=$(date +%s)
cat $1 | parallel -j$2 -u ./src/ceres {}
end_time=$(date +%s)

echo "parallel runs took $[$end_time - $start_time] seconds"




